<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.4.1)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateTicketTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('ticket', function (Blueprint $table) {
            $table->increments('id');
            $table->string('name', 255);
            $table->integer('duration');
            $table->double('price');
            $table->text('content');
            $table->enum('type', ['child', 'normal', 'family']);
            $table->text('config');
            $table->nullableTimestamps();
            $table->enum('status', ['enable', 'disable']);
            $table->string('slug', 255);
            $table->string('image_url', 255);

            

            

        });

        

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('ticket');
    }
}
